// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package ds.userService;

public interface LoginResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:userService.LoginResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string responseMessage = 1;</code>
   */
  java.lang.String getResponseMessage();
  /**
   * <code>string responseMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getResponseMessageBytes();

  /**
   * <code>int32 responseCode = 2;</code>
   */
  int getResponseCode();

  /**
   * <code>string jwtToken = 3;</code>
   */
  java.lang.String getJwtToken();
  /**
   * <code>string jwtToken = 3;</code>
   */
  com.google.protobuf.ByteString
      getJwtTokenBytes();
}
