// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserService.proto

package ds.userService;

public final class UserServiceImpl {
  private UserServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userService_LoginRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userService_LoginRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userService_LoginResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userService_LoginResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userService_LogoutRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userService_LogoutRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_userService_LogoutResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_userService_LogoutResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021UserService.proto\022\013userService\"2\n\014Logi" +
      "nRequest\022\020\n\010username\030\001 \001(\t\022\020\n\010password\030\002" +
      " \001(\t\"P\n\rLoginResponse\022\027\n\017responseMessage" +
      "\030\001 \001(\t\022\024\n\014responseCode\030\002 \001(\005\022\020\n\010jwtToken" +
      "\030\003 \001(\t\"!\n\rLogoutRequest\022\020\n\010username\030\001 \001(" +
      "\t\"?\n\016LogoutResponse\022\027\n\017responseMessage\030\001" +
      " \001(\t\022\024\n\014responseCode\030\002 \001(\0052\224\001\n\013UserServi" +
      "ce\022@\n\005login\022\031.userService.LoginRequest\032\032" +
      ".userService.LoginResponse\"\000\022C\n\006logout\022\032" +
      ".userService.LogoutRequest\032\033.userService" +
      ".LogoutResponse\"\000B#\n\016ds.userServiceB\017Use" +
      "rServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_userService_LoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_userService_LoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userService_LoginRequest_descriptor,
        new java.lang.String[] { "Username", "Password", });
    internal_static_userService_LoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_userService_LoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userService_LoginResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", "JwtToken", });
    internal_static_userService_LogoutRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_userService_LogoutRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userService_LogoutRequest_descriptor,
        new java.lang.String[] { "Username", });
    internal_static_userService_LogoutResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_userService_LogoutResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_userService_LogoutResponse_descriptor,
        new java.lang.String[] { "ResponseMessage", "ResponseCode", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
