// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

public interface AnimalTimeSpanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestockActivityService.AnimalTimeSpan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string startDate = 1;</code>
   */
  java.lang.String getStartDate();
  /**
   * <code>string startDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string endDate = 2;</code>
   */
  java.lang.String getEndDate();
  /**
   * <code>string endDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getEndDateBytes();

  /**
   * <code>.livestockActivityService.AnimalId animalID = 3;</code>
   */
  boolean hasAnimalID();
  /**
   * <code>.livestockActivityService.AnimalId animalID = 3;</code>
   */
  ds.livestockActivityService.AnimalId getAnimalID();
  /**
   * <code>.livestockActivityService.AnimalId animalID = 3;</code>
   */
  ds.livestockActivityService.AnimalIdOrBuilder getAnimalIDOrBuilder();
}
