// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

public interface AnimalHealthInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestockActivityService.AnimalHealthInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reportDate = 1;</code>
   */
  java.lang.String getReportDate();
  /**
   * <code>string reportDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getReportDateBytes();

  /**
   * <code>int32 minBPM = 2;</code>
   */
  int getMinBPM();

  /**
   * <code>int32 maxBPM = 3;</code>
   */
  int getMaxBPM();

  /**
   * <code>int32 avgBPM = 4;</code>
   */
  int getAvgBPM();

  /**
   * <code>.livestockActivityService.AnimalHealthInfo.Health healthIndicator = 5;</code>
   */
  int getHealthIndicatorValue();
  /**
   * <code>.livestockActivityService.AnimalHealthInfo.Health healthIndicator = 5;</code>
   */
  ds.livestockActivityService.AnimalHealthInfo.Health getHealthIndicator();

  /**
   * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
   */
  boolean hasAnimal();
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
   */
  ds.livestockActivityService.AnimalDetail getAnimal();
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
   */
  ds.livestockActivityService.AnimalDetailOrBuilder getAnimalOrBuilder();
}
