// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

public interface AnimalIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestockActivityService.AnimalId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
