// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

/**
 * Protobuf type {@code livestockActivityService.AnimalHealthInfo}
 */
public  final class AnimalHealthInfo extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:livestockActivityService.AnimalHealthInfo)
    AnimalHealthInfoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AnimalHealthInfo.newBuilder() to construct.
  private AnimalHealthInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AnimalHealthInfo() {
    reportDate_ = "";
    minBPM_ = 0;
    maxBPM_ = 0;
    avgBPM_ = 0;
    healthIndicator_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AnimalHealthInfo(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            reportDate_ = s;
            break;
          }
          case 16: {

            minBPM_ = input.readInt32();
            break;
          }
          case 24: {

            maxBPM_ = input.readInt32();
            break;
          }
          case 32: {

            avgBPM_ = input.readInt32();
            break;
          }
          case 40: {
            int rawValue = input.readEnum();

            healthIndicator_ = rawValue;
            break;
          }
          case 50: {
            ds.livestockActivityService.AnimalDetail.Builder subBuilder = null;
            if (animal_ != null) {
              subBuilder = animal_.toBuilder();
            }
            animal_ = input.readMessage(ds.livestockActivityService.AnimalDetail.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(animal_);
              animal_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_AnimalHealthInfo_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_AnimalHealthInfo_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.livestockActivityService.AnimalHealthInfo.class, ds.livestockActivityService.AnimalHealthInfo.Builder.class);
  }

  /**
   * Protobuf enum {@code livestockActivityService.AnimalHealthInfo.Health}
   */
  public enum Health
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>healthy = 0;</code>
     */
    healthy(0),
    /**
     * <code>vaccineDue = 1;</code>
     */
    vaccineDue(1),
    /**
     * <code>highHeartRate = 2;</code>
     */
    highHeartRate(2),
    /**
     * <code>lowHeartRate = 3;</code>
     */
    lowHeartRate(3),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>healthy = 0;</code>
     */
    public static final int healthy_VALUE = 0;
    /**
     * <code>vaccineDue = 1;</code>
     */
    public static final int vaccineDue_VALUE = 1;
    /**
     * <code>highHeartRate = 2;</code>
     */
    public static final int highHeartRate_VALUE = 2;
    /**
     * <code>lowHeartRate = 3;</code>
     */
    public static final int lowHeartRate_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Health valueOf(int value) {
      return forNumber(value);
    }

    public static Health forNumber(int value) {
      switch (value) {
        case 0: return healthy;
        case 1: return vaccineDue;
        case 2: return highHeartRate;
        case 3: return lowHeartRate;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Health>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Health> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Health>() {
            public Health findValueByNumber(int number) {
              return Health.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ds.livestockActivityService.AnimalHealthInfo.getDescriptor().getEnumTypes().get(0);
    }

    private static final Health[] VALUES = values();

    public static Health valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Health(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:livestockActivityService.AnimalHealthInfo.Health)
  }

  public static final int REPORTDATE_FIELD_NUMBER = 1;
  private volatile java.lang.Object reportDate_;
  /**
   * <code>string reportDate = 1;</code>
   */
  public java.lang.String getReportDate() {
    java.lang.Object ref = reportDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      reportDate_ = s;
      return s;
    }
  }
  /**
   * <code>string reportDate = 1;</code>
   */
  public com.google.protobuf.ByteString
      getReportDateBytes() {
    java.lang.Object ref = reportDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      reportDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MINBPM_FIELD_NUMBER = 2;
  private int minBPM_;
  /**
   * <code>int32 minBPM = 2;</code>
   */
  public int getMinBPM() {
    return minBPM_;
  }

  public static final int MAXBPM_FIELD_NUMBER = 3;
  private int maxBPM_;
  /**
   * <code>int32 maxBPM = 3;</code>
   */
  public int getMaxBPM() {
    return maxBPM_;
  }

  public static final int AVGBPM_FIELD_NUMBER = 4;
  private int avgBPM_;
  /**
   * <code>int32 avgBPM = 4;</code>
   */
  public int getAvgBPM() {
    return avgBPM_;
  }

  public static final int HEALTHINDICATOR_FIELD_NUMBER = 5;
  private int healthIndicator_;
  /**
   * <code>.livestockActivityService.AnimalHealthInfo.Health healthIndicator = 5;</code>
   */
  public int getHealthIndicatorValue() {
    return healthIndicator_;
  }
  /**
   * <code>.livestockActivityService.AnimalHealthInfo.Health healthIndicator = 5;</code>
   */
  public ds.livestockActivityService.AnimalHealthInfo.Health getHealthIndicator() {
    @SuppressWarnings("deprecation")
    ds.livestockActivityService.AnimalHealthInfo.Health result = ds.livestockActivityService.AnimalHealthInfo.Health.valueOf(healthIndicator_);
    return result == null ? ds.livestockActivityService.AnimalHealthInfo.Health.UNRECOGNIZED : result;
  }

  public static final int ANIMAL_FIELD_NUMBER = 6;
  private ds.livestockActivityService.AnimalDetail animal_;
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
   */
  public boolean hasAnimal() {
    return animal_ != null;
  }
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
   */
  public ds.livestockActivityService.AnimalDetail getAnimal() {
    return animal_ == null ? ds.livestockActivityService.AnimalDetail.getDefaultInstance() : animal_;
  }
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
   */
  public ds.livestockActivityService.AnimalDetailOrBuilder getAnimalOrBuilder() {
    return getAnimal();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getReportDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, reportDate_);
    }
    if (minBPM_ != 0) {
      output.writeInt32(2, minBPM_);
    }
    if (maxBPM_ != 0) {
      output.writeInt32(3, maxBPM_);
    }
    if (avgBPM_ != 0) {
      output.writeInt32(4, avgBPM_);
    }
    if (healthIndicator_ != ds.livestockActivityService.AnimalHealthInfo.Health.healthy.getNumber()) {
      output.writeEnum(5, healthIndicator_);
    }
    if (animal_ != null) {
      output.writeMessage(6, getAnimal());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getReportDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, reportDate_);
    }
    if (minBPM_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, minBPM_);
    }
    if (maxBPM_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, maxBPM_);
    }
    if (avgBPM_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, avgBPM_);
    }
    if (healthIndicator_ != ds.livestockActivityService.AnimalHealthInfo.Health.healthy.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(5, healthIndicator_);
    }
    if (animal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getAnimal());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.livestockActivityService.AnimalHealthInfo)) {
      return super.equals(obj);
    }
    ds.livestockActivityService.AnimalHealthInfo other = (ds.livestockActivityService.AnimalHealthInfo) obj;

    boolean result = true;
    result = result && getReportDate()
        .equals(other.getReportDate());
    result = result && (getMinBPM()
        == other.getMinBPM());
    result = result && (getMaxBPM()
        == other.getMaxBPM());
    result = result && (getAvgBPM()
        == other.getAvgBPM());
    result = result && healthIndicator_ == other.healthIndicator_;
    result = result && (hasAnimal() == other.hasAnimal());
    if (hasAnimal()) {
      result = result && getAnimal()
          .equals(other.getAnimal());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + REPORTDATE_FIELD_NUMBER;
    hash = (53 * hash) + getReportDate().hashCode();
    hash = (37 * hash) + MINBPM_FIELD_NUMBER;
    hash = (53 * hash) + getMinBPM();
    hash = (37 * hash) + MAXBPM_FIELD_NUMBER;
    hash = (53 * hash) + getMaxBPM();
    hash = (37 * hash) + AVGBPM_FIELD_NUMBER;
    hash = (53 * hash) + getAvgBPM();
    hash = (37 * hash) + HEALTHINDICATOR_FIELD_NUMBER;
    hash = (53 * hash) + healthIndicator_;
    if (hasAnimal()) {
      hash = (37 * hash) + ANIMAL_FIELD_NUMBER;
      hash = (53 * hash) + getAnimal().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.livestockActivityService.AnimalHealthInfo parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.livestockActivityService.AnimalHealthInfo prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code livestockActivityService.AnimalHealthInfo}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:livestockActivityService.AnimalHealthInfo)
      ds.livestockActivityService.AnimalHealthInfoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_AnimalHealthInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_AnimalHealthInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.livestockActivityService.AnimalHealthInfo.class, ds.livestockActivityService.AnimalHealthInfo.Builder.class);
    }

    // Construct using ds.livestockActivityService.AnimalHealthInfo.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      reportDate_ = "";

      minBPM_ = 0;

      maxBPM_ = 0;

      avgBPM_ = 0;

      healthIndicator_ = 0;

      if (animalBuilder_ == null) {
        animal_ = null;
      } else {
        animal_ = null;
        animalBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_AnimalHealthInfo_descriptor;
    }

    @java.lang.Override
    public ds.livestockActivityService.AnimalHealthInfo getDefaultInstanceForType() {
      return ds.livestockActivityService.AnimalHealthInfo.getDefaultInstance();
    }

    @java.lang.Override
    public ds.livestockActivityService.AnimalHealthInfo build() {
      ds.livestockActivityService.AnimalHealthInfo result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.livestockActivityService.AnimalHealthInfo buildPartial() {
      ds.livestockActivityService.AnimalHealthInfo result = new ds.livestockActivityService.AnimalHealthInfo(this);
      result.reportDate_ = reportDate_;
      result.minBPM_ = minBPM_;
      result.maxBPM_ = maxBPM_;
      result.avgBPM_ = avgBPM_;
      result.healthIndicator_ = healthIndicator_;
      if (animalBuilder_ == null) {
        result.animal_ = animal_;
      } else {
        result.animal_ = animalBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.livestockActivityService.AnimalHealthInfo) {
        return mergeFrom((ds.livestockActivityService.AnimalHealthInfo)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.livestockActivityService.AnimalHealthInfo other) {
      if (other == ds.livestockActivityService.AnimalHealthInfo.getDefaultInstance()) return this;
      if (!other.getReportDate().isEmpty()) {
        reportDate_ = other.reportDate_;
        onChanged();
      }
      if (other.getMinBPM() != 0) {
        setMinBPM(other.getMinBPM());
      }
      if (other.getMaxBPM() != 0) {
        setMaxBPM(other.getMaxBPM());
      }
      if (other.getAvgBPM() != 0) {
        setAvgBPM(other.getAvgBPM());
      }
      if (other.healthIndicator_ != 0) {
        setHealthIndicatorValue(other.getHealthIndicatorValue());
      }
      if (other.hasAnimal()) {
        mergeAnimal(other.getAnimal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.livestockActivityService.AnimalHealthInfo parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.livestockActivityService.AnimalHealthInfo) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object reportDate_ = "";
    /**
     * <code>string reportDate = 1;</code>
     */
    public java.lang.String getReportDate() {
      java.lang.Object ref = reportDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        reportDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string reportDate = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReportDateBytes() {
      java.lang.Object ref = reportDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        reportDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string reportDate = 1;</code>
     */
    public Builder setReportDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      reportDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string reportDate = 1;</code>
     */
    public Builder clearReportDate() {
      
      reportDate_ = getDefaultInstance().getReportDate();
      onChanged();
      return this;
    }
    /**
     * <code>string reportDate = 1;</code>
     */
    public Builder setReportDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      reportDate_ = value;
      onChanged();
      return this;
    }

    private int minBPM_ ;
    /**
     * <code>int32 minBPM = 2;</code>
     */
    public int getMinBPM() {
      return minBPM_;
    }
    /**
     * <code>int32 minBPM = 2;</code>
     */
    public Builder setMinBPM(int value) {
      
      minBPM_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 minBPM = 2;</code>
     */
    public Builder clearMinBPM() {
      
      minBPM_ = 0;
      onChanged();
      return this;
    }

    private int maxBPM_ ;
    /**
     * <code>int32 maxBPM = 3;</code>
     */
    public int getMaxBPM() {
      return maxBPM_;
    }
    /**
     * <code>int32 maxBPM = 3;</code>
     */
    public Builder setMaxBPM(int value) {
      
      maxBPM_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 maxBPM = 3;</code>
     */
    public Builder clearMaxBPM() {
      
      maxBPM_ = 0;
      onChanged();
      return this;
    }

    private int avgBPM_ ;
    /**
     * <code>int32 avgBPM = 4;</code>
     */
    public int getAvgBPM() {
      return avgBPM_;
    }
    /**
     * <code>int32 avgBPM = 4;</code>
     */
    public Builder setAvgBPM(int value) {
      
      avgBPM_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 avgBPM = 4;</code>
     */
    public Builder clearAvgBPM() {
      
      avgBPM_ = 0;
      onChanged();
      return this;
    }

    private int healthIndicator_ = 0;
    /**
     * <code>.livestockActivityService.AnimalHealthInfo.Health healthIndicator = 5;</code>
     */
    public int getHealthIndicatorValue() {
      return healthIndicator_;
    }
    /**
     * <code>.livestockActivityService.AnimalHealthInfo.Health healthIndicator = 5;</code>
     */
    public Builder setHealthIndicatorValue(int value) {
      healthIndicator_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalHealthInfo.Health healthIndicator = 5;</code>
     */
    public ds.livestockActivityService.AnimalHealthInfo.Health getHealthIndicator() {
      @SuppressWarnings("deprecation")
      ds.livestockActivityService.AnimalHealthInfo.Health result = ds.livestockActivityService.AnimalHealthInfo.Health.valueOf(healthIndicator_);
      return result == null ? ds.livestockActivityService.AnimalHealthInfo.Health.UNRECOGNIZED : result;
    }
    /**
     * <code>.livestockActivityService.AnimalHealthInfo.Health healthIndicator = 5;</code>
     */
    public Builder setHealthIndicator(ds.livestockActivityService.AnimalHealthInfo.Health value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      healthIndicator_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalHealthInfo.Health healthIndicator = 5;</code>
     */
    public Builder clearHealthIndicator() {
      
      healthIndicator_ = 0;
      onChanged();
      return this;
    }

    private ds.livestockActivityService.AnimalDetail animal_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.livestockActivityService.AnimalDetail, ds.livestockActivityService.AnimalDetail.Builder, ds.livestockActivityService.AnimalDetailOrBuilder> animalBuilder_;
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
     */
    public boolean hasAnimal() {
      return animalBuilder_ != null || animal_ != null;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
     */
    public ds.livestockActivityService.AnimalDetail getAnimal() {
      if (animalBuilder_ == null) {
        return animal_ == null ? ds.livestockActivityService.AnimalDetail.getDefaultInstance() : animal_;
      } else {
        return animalBuilder_.getMessage();
      }
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
     */
    public Builder setAnimal(ds.livestockActivityService.AnimalDetail value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        animal_ = value;
        onChanged();
      } else {
        animalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
     */
    public Builder setAnimal(
        ds.livestockActivityService.AnimalDetail.Builder builderForValue) {
      if (animalBuilder_ == null) {
        animal_ = builderForValue.build();
        onChanged();
      } else {
        animalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
     */
    public Builder mergeAnimal(ds.livestockActivityService.AnimalDetail value) {
      if (animalBuilder_ == null) {
        if (animal_ != null) {
          animal_ =
            ds.livestockActivityService.AnimalDetail.newBuilder(animal_).mergeFrom(value).buildPartial();
        } else {
          animal_ = value;
        }
        onChanged();
      } else {
        animalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
     */
    public Builder clearAnimal() {
      if (animalBuilder_ == null) {
        animal_ = null;
        onChanged();
      } else {
        animal_ = null;
        animalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
     */
    public ds.livestockActivityService.AnimalDetail.Builder getAnimalBuilder() {
      
      onChanged();
      return getAnimalFieldBuilder().getBuilder();
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
     */
    public ds.livestockActivityService.AnimalDetailOrBuilder getAnimalOrBuilder() {
      if (animalBuilder_ != null) {
        return animalBuilder_.getMessageOrBuilder();
      } else {
        return animal_ == null ?
            ds.livestockActivityService.AnimalDetail.getDefaultInstance() : animal_;
      }
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.livestockActivityService.AnimalDetail, ds.livestockActivityService.AnimalDetail.Builder, ds.livestockActivityService.AnimalDetailOrBuilder> 
        getAnimalFieldBuilder() {
      if (animalBuilder_ == null) {
        animalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ds.livestockActivityService.AnimalDetail, ds.livestockActivityService.AnimalDetail.Builder, ds.livestockActivityService.AnimalDetailOrBuilder>(
                getAnimal(),
                getParentForChildren(),
                isClean());
        animal_ = null;
      }
      return animalBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:livestockActivityService.AnimalHealthInfo)
  }

  // @@protoc_insertion_point(class_scope:livestockActivityService.AnimalHealthInfo)
  private static final ds.livestockActivityService.AnimalHealthInfo DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.livestockActivityService.AnimalHealthInfo();
  }

  public static ds.livestockActivityService.AnimalHealthInfo getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AnimalHealthInfo>
      PARSER = new com.google.protobuf.AbstractParser<AnimalHealthInfo>() {
    @java.lang.Override
    public AnimalHealthInfo parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AnimalHealthInfo(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AnimalHealthInfo> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AnimalHealthInfo> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.livestockActivityService.AnimalHealthInfo getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

