// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

/**
 * Protobuf type {@code livestockActivityService.CurrentActivity}
 */
public  final class CurrentActivity extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:livestockActivityService.CurrentActivity)
    CurrentActivityOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CurrentActivity.newBuilder() to construct.
  private CurrentActivity(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CurrentActivity() {
    activity_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CurrentActivity(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            ds.livestockActivityService.AnimalDetail.Builder subBuilder = null;
            if (animal_ != null) {
              subBuilder = animal_.toBuilder();
            }
            animal_ = input.readMessage(ds.livestockActivityService.AnimalDetail.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(animal_);
              animal_ = subBuilder.buildPartial();
            }

            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            activity_ = rawValue;
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_CurrentActivity_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_CurrentActivity_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ds.livestockActivityService.CurrentActivity.class, ds.livestockActivityService.CurrentActivity.Builder.class);
  }

  /**
   * Protobuf enum {@code livestockActivityService.CurrentActivity.Activity}
   */
  public enum Activity
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>standing = 0;</code>
     */
    standing(0),
    /**
     * <code>feeding = 1;</code>
     */
    feeding(1),
    /**
     * <code>drinking = 2;</code>
     */
    drinking(2),
    /**
     * <code>lying = 3;</code>
     */
    lying(3),
    /**
     * <code>moving = 4;</code>
     */
    moving(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>standing = 0;</code>
     */
    public static final int standing_VALUE = 0;
    /**
     * <code>feeding = 1;</code>
     */
    public static final int feeding_VALUE = 1;
    /**
     * <code>drinking = 2;</code>
     */
    public static final int drinking_VALUE = 2;
    /**
     * <code>lying = 3;</code>
     */
    public static final int lying_VALUE = 3;
    /**
     * <code>moving = 4;</code>
     */
    public static final int moving_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Activity valueOf(int value) {
      return forNumber(value);
    }

    public static Activity forNumber(int value) {
      switch (value) {
        case 0: return standing;
        case 1: return feeding;
        case 2: return drinking;
        case 3: return lying;
        case 4: return moving;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Activity>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Activity> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Activity>() {
            public Activity findValueByNumber(int number) {
              return Activity.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ds.livestockActivityService.CurrentActivity.getDescriptor().getEnumTypes().get(0);
    }

    private static final Activity[] VALUES = values();

    public static Activity valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Activity(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:livestockActivityService.CurrentActivity.Activity)
  }

  public static final int ANIMAL_FIELD_NUMBER = 1;
  private ds.livestockActivityService.AnimalDetail animal_;
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
   */
  public boolean hasAnimal() {
    return animal_ != null;
  }
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
   */
  public ds.livestockActivityService.AnimalDetail getAnimal() {
    return animal_ == null ? ds.livestockActivityService.AnimalDetail.getDefaultInstance() : animal_;
  }
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
   */
  public ds.livestockActivityService.AnimalDetailOrBuilder getAnimalOrBuilder() {
    return getAnimal();
  }

  public static final int ACTIVITY_FIELD_NUMBER = 2;
  private int activity_;
  /**
   * <code>.livestockActivityService.CurrentActivity.Activity activity = 2;</code>
   */
  public int getActivityValue() {
    return activity_;
  }
  /**
   * <code>.livestockActivityService.CurrentActivity.Activity activity = 2;</code>
   */
  public ds.livestockActivityService.CurrentActivity.Activity getActivity() {
    @SuppressWarnings("deprecation")
    ds.livestockActivityService.CurrentActivity.Activity result = ds.livestockActivityService.CurrentActivity.Activity.valueOf(activity_);
    return result == null ? ds.livestockActivityService.CurrentActivity.Activity.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (animal_ != null) {
      output.writeMessage(1, getAnimal());
    }
    if (activity_ != ds.livestockActivityService.CurrentActivity.Activity.standing.getNumber()) {
      output.writeEnum(2, activity_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (animal_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getAnimal());
    }
    if (activity_ != ds.livestockActivityService.CurrentActivity.Activity.standing.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, activity_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof ds.livestockActivityService.CurrentActivity)) {
      return super.equals(obj);
    }
    ds.livestockActivityService.CurrentActivity other = (ds.livestockActivityService.CurrentActivity) obj;

    boolean result = true;
    result = result && (hasAnimal() == other.hasAnimal());
    if (hasAnimal()) {
      result = result && getAnimal()
          .equals(other.getAnimal());
    }
    result = result && activity_ == other.activity_;
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasAnimal()) {
      hash = (37 * hash) + ANIMAL_FIELD_NUMBER;
      hash = (53 * hash) + getAnimal().hashCode();
    }
    hash = (37 * hash) + ACTIVITY_FIELD_NUMBER;
    hash = (53 * hash) + activity_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static ds.livestockActivityService.CurrentActivity parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.livestockActivityService.CurrentActivity parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.livestockActivityService.CurrentActivity parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.livestockActivityService.CurrentActivity parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.livestockActivityService.CurrentActivity parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ds.livestockActivityService.CurrentActivity parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ds.livestockActivityService.CurrentActivity parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.livestockActivityService.CurrentActivity parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.livestockActivityService.CurrentActivity parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ds.livestockActivityService.CurrentActivity parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ds.livestockActivityService.CurrentActivity parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ds.livestockActivityService.CurrentActivity parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ds.livestockActivityService.CurrentActivity prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code livestockActivityService.CurrentActivity}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:livestockActivityService.CurrentActivity)
      ds.livestockActivityService.CurrentActivityOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_CurrentActivity_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_CurrentActivity_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ds.livestockActivityService.CurrentActivity.class, ds.livestockActivityService.CurrentActivity.Builder.class);
    }

    // Construct using ds.livestockActivityService.CurrentActivity.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (animalBuilder_ == null) {
        animal_ = null;
      } else {
        animal_ = null;
        animalBuilder_ = null;
      }
      activity_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ds.livestockActivityService.LivestockActivityServiceImpl.internal_static_livestockActivityService_CurrentActivity_descriptor;
    }

    @java.lang.Override
    public ds.livestockActivityService.CurrentActivity getDefaultInstanceForType() {
      return ds.livestockActivityService.CurrentActivity.getDefaultInstance();
    }

    @java.lang.Override
    public ds.livestockActivityService.CurrentActivity build() {
      ds.livestockActivityService.CurrentActivity result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ds.livestockActivityService.CurrentActivity buildPartial() {
      ds.livestockActivityService.CurrentActivity result = new ds.livestockActivityService.CurrentActivity(this);
      if (animalBuilder_ == null) {
        result.animal_ = animal_;
      } else {
        result.animal_ = animalBuilder_.build();
      }
      result.activity_ = activity_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof ds.livestockActivityService.CurrentActivity) {
        return mergeFrom((ds.livestockActivityService.CurrentActivity)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(ds.livestockActivityService.CurrentActivity other) {
      if (other == ds.livestockActivityService.CurrentActivity.getDefaultInstance()) return this;
      if (other.hasAnimal()) {
        mergeAnimal(other.getAnimal());
      }
      if (other.activity_ != 0) {
        setActivityValue(other.getActivityValue());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      ds.livestockActivityService.CurrentActivity parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (ds.livestockActivityService.CurrentActivity) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private ds.livestockActivityService.AnimalDetail animal_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.livestockActivityService.AnimalDetail, ds.livestockActivityService.AnimalDetail.Builder, ds.livestockActivityService.AnimalDetailOrBuilder> animalBuilder_;
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
     */
    public boolean hasAnimal() {
      return animalBuilder_ != null || animal_ != null;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
     */
    public ds.livestockActivityService.AnimalDetail getAnimal() {
      if (animalBuilder_ == null) {
        return animal_ == null ? ds.livestockActivityService.AnimalDetail.getDefaultInstance() : animal_;
      } else {
        return animalBuilder_.getMessage();
      }
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
     */
    public Builder setAnimal(ds.livestockActivityService.AnimalDetail value) {
      if (animalBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        animal_ = value;
        onChanged();
      } else {
        animalBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
     */
    public Builder setAnimal(
        ds.livestockActivityService.AnimalDetail.Builder builderForValue) {
      if (animalBuilder_ == null) {
        animal_ = builderForValue.build();
        onChanged();
      } else {
        animalBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
     */
    public Builder mergeAnimal(ds.livestockActivityService.AnimalDetail value) {
      if (animalBuilder_ == null) {
        if (animal_ != null) {
          animal_ =
            ds.livestockActivityService.AnimalDetail.newBuilder(animal_).mergeFrom(value).buildPartial();
        } else {
          animal_ = value;
        }
        onChanged();
      } else {
        animalBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
     */
    public Builder clearAnimal() {
      if (animalBuilder_ == null) {
        animal_ = null;
        onChanged();
      } else {
        animal_ = null;
        animalBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
     */
    public ds.livestockActivityService.AnimalDetail.Builder getAnimalBuilder() {
      
      onChanged();
      return getAnimalFieldBuilder().getBuilder();
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
     */
    public ds.livestockActivityService.AnimalDetailOrBuilder getAnimalOrBuilder() {
      if (animalBuilder_ != null) {
        return animalBuilder_.getMessageOrBuilder();
      } else {
        return animal_ == null ?
            ds.livestockActivityService.AnimalDetail.getDefaultInstance() : animal_;
      }
    }
    /**
     * <code>.livestockActivityService.AnimalDetail animal = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        ds.livestockActivityService.AnimalDetail, ds.livestockActivityService.AnimalDetail.Builder, ds.livestockActivityService.AnimalDetailOrBuilder> 
        getAnimalFieldBuilder() {
      if (animalBuilder_ == null) {
        animalBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            ds.livestockActivityService.AnimalDetail, ds.livestockActivityService.AnimalDetail.Builder, ds.livestockActivityService.AnimalDetailOrBuilder>(
                getAnimal(),
                getParentForChildren(),
                isClean());
        animal_ = null;
      }
      return animalBuilder_;
    }

    private int activity_ = 0;
    /**
     * <code>.livestockActivityService.CurrentActivity.Activity activity = 2;</code>
     */
    public int getActivityValue() {
      return activity_;
    }
    /**
     * <code>.livestockActivityService.CurrentActivity.Activity activity = 2;</code>
     */
    public Builder setActivityValue(int value) {
      activity_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.livestockActivityService.CurrentActivity.Activity activity = 2;</code>
     */
    public ds.livestockActivityService.CurrentActivity.Activity getActivity() {
      @SuppressWarnings("deprecation")
      ds.livestockActivityService.CurrentActivity.Activity result = ds.livestockActivityService.CurrentActivity.Activity.valueOf(activity_);
      return result == null ? ds.livestockActivityService.CurrentActivity.Activity.UNRECOGNIZED : result;
    }
    /**
     * <code>.livestockActivityService.CurrentActivity.Activity activity = 2;</code>
     */
    public Builder setActivity(ds.livestockActivityService.CurrentActivity.Activity value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      activity_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.livestockActivityService.CurrentActivity.Activity activity = 2;</code>
     */
    public Builder clearActivity() {
      
      activity_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:livestockActivityService.CurrentActivity)
  }

  // @@protoc_insertion_point(class_scope:livestockActivityService.CurrentActivity)
  private static final ds.livestockActivityService.CurrentActivity DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ds.livestockActivityService.CurrentActivity();
  }

  public static ds.livestockActivityService.CurrentActivity getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CurrentActivity>
      PARSER = new com.google.protobuf.AbstractParser<CurrentActivity>() {
    @java.lang.Override
    public CurrentActivity parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CurrentActivity(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CurrentActivity> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CurrentActivity> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ds.livestockActivityService.CurrentActivity getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

