// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

public interface CurrentActivityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestockActivityService.CurrentActivity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.livestockActivityService.AnimalId animalID = 1;</code>
   */
  boolean hasAnimalID();
  /**
   * <code>.livestockActivityService.AnimalId animalID = 1;</code>
   */
  ds.livestockActivityService.AnimalId getAnimalID();
  /**
   * <code>.livestockActivityService.AnimalId animalID = 1;</code>
   */
  ds.livestockActivityService.AnimalIdOrBuilder getAnimalIDOrBuilder();

  /**
   * <code>.livestockActivityService.CurrentActivity.Activity activity = 2;</code>
   */
  int getActivityValue();
  /**
   * <code>.livestockActivityService.CurrentActivity.Activity activity = 2;</code>
   */
  ds.livestockActivityService.CurrentActivity.Activity getActivity();
}
