// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestockActivityService.Empty)
    com.google.protobuf.MessageOrBuilder {
}
