// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

public interface HeartRateHistoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestockActivityService.HeartRateHistory)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bpm = 1;</code>
   */
  int getBpm();

  /**
   * <code>string timeStamp = 2;</code>
   */
  java.lang.String getTimeStamp();
  /**
   * <code>string timeStamp = 2;</code>
   */
  com.google.protobuf.ByteString
      getTimeStampBytes();

  /**
   * <code>.livestockActivityService.AnimalDetail animal = 3;</code>
   */
  boolean hasAnimal();
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 3;</code>
   */
  ds.livestockActivityService.AnimalDetail getAnimal();
  /**
   * <code>.livestockActivityService.AnimalDetail animal = 3;</code>
   */
  ds.livestockActivityService.AnimalDetailOrBuilder getAnimalOrBuilder();
}
