// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

public final class LivestockActivityServiceImpl {
  private LivestockActivityServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestockActivityService_AnimalId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestockActivityService_AnimalId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestockActivityService_AnimalDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestockActivityService_AnimalDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestockActivityService_SetAnimalDetailsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestockActivityService_SetAnimalDetailsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestockActivityService_AnimalTimeSpan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestockActivityService_AnimalTimeSpan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestockActivityService_LiveHeartRate_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestockActivityService_LiveHeartRate_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestockActivityService_HeartRateHistory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestockActivityService_HeartRateHistory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestockActivityService_CurrentActivity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestockActivityService_CurrentActivity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestockActivityService_AnimalHealthInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestockActivityService_AnimalHealthInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_livestockActivityService_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_livestockActivityService_Empty_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036LivestockActivityService.proto\022\030livest" +
      "ockActivityService\"\026\n\010AnimalId\022\n\n\002id\030\001 \001" +
      "(\005\"\366\001\n\014AnimalDetail\0224\n\010animalID\030\001 \001(\0132\"." +
      "livestockActivityService.AnimalId\022I\n\014typ" +
      "eOfAnimal\030\002 \001(\01623.livestockActivityServi" +
      "ce.AnimalDetail.TypeOfAnimal\022\023\n\013dateOfBi" +
      "rth\030\003 \001(\t\022\027\n\017dateNextVaccine\030\004 \001(\t\"7\n\014Ty" +
      "peOfAnimal\022\007\n\003COW\020\000\022\t\n\005SHEEP\020\001\022\t\n\005HORSE\020" +
      "\002\022\010\n\004GOAT\020\003\"6\n\025SetAnimalDetailsReply\022\035\n\025" +
      "setAnimalDetailsReply\030\001 \001(\t\"j\n\016AnimalTim" +
      "eSpan\022\021\n\tstartDate\030\001 \001(\t\022\017\n\007endDate\030\002 \001(" +
      "\t\0224\n\010animalID\030\003 \001(\0132\".livestockActivityS" +
      "ervice.AnimalId\"T\n\rLiveHeartRate\022\013\n\003bpm\030" +
      "\001 \001(\005\0226\n\006animal\030\002 \001(\0132&.livestockActivit" +
      "yService.AnimalDetail\"j\n\020HeartRateHistor" +
      "y\022\013\n\003bpm\030\001 \001(\005\022\021\n\ttimeStamp\030\002 \001(\t\0226\n\006ani" +
      "mal\030\003 \001(\0132&.livestockActivityService.Ani" +
      "malDetail\"\333\001\n\017CurrentActivity\0226\n\006animal\030" +
      "\001 \001(\0132&.livestockActivityService.AnimalD" +
      "etail\022D\n\010activity\030\002 \001(\01622.livestockActiv" +
      "ityService.CurrentActivity.Activity\"J\n\010A" +
      "ctivity\022\014\n\010standing\020\000\022\013\n\007feeding\020\001\022\014\n\010dr" +
      "inking\020\002\022\t\n\005lying\020\003\022\n\n\006moving\020\004\"\246\002\n\020Anim" +
      "alHealthInfo\022\022\n\nreportDate\030\001 \001(\t\022\016\n\006minB" +
      "PM\030\002 \001(\005\022\016\n\006maxBPM\030\003 \001(\005\022\016\n\006avgBPM\030\004 \001(\005" +
      "\022J\n\017healthIndicator\030\005 \001(\01621.livestockAct" +
      "ivityService.AnimalHealthInfo.Health\0226\n\006" +
      "animal\030\006 \001(\0132&.livestockActivityService." +
      "AnimalDetail\"J\n\006Health\022\013\n\007healthy\020\000\022\016\n\nv" +
      "accineDue\020\001\022\021\n\rhighHeartRate\020\002\022\020\n\014lowHea" +
      "rtRate\020\003\"\007\n\005Empty2\212\005\n\030LivestockActivityS" +
      "ervice\022o\n\020SetAnimalDetails\022&.livestockAc" +
      "tivityService.AnimalDetail\032/.livestockAc" +
      "tivityService.SetAnimalDetailsReply\"\000(\001\022" +
      "W\n\014GetAnimalIds\022\037.livestockActivityServi" +
      "ce.Empty\032\".livestockActivityService.Anim" +
      "alId\"\0000\001\022c\n\020GetLiveHeartRate\022\".livestock" +
      "ActivityService.AnimalId\032\'.livestockActi" +
      "vityService.LiveHeartRate\"\0000\001\022o\n\023GetHear" +
      "tRateHistory\022(.livestockActivityService." +
      "AnimalTimeSpan\032*.livestockActivityServic" +
      "e.HeartRateHistory\"\0000\001\022e\n\022GetCurrentActi" +
      "vity\022\".livestockActivityService.AnimalId" +
      "\032).livestockActivityService.CurrentActiv" +
      "ity\"\000\022g\n\017GetAnimalVitals\022\".livestockActi" +
      "vityService.AnimalId\032*.livestockActivity" +
      "Service.AnimalHealthInfo\"\000(\0010\001B=\n\033ds.liv" +
      "estockActivityServiceB\034LivestockActivity" +
      "ServiceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_livestockActivityService_AnimalId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_livestockActivityService_AnimalId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestockActivityService_AnimalId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_livestockActivityService_AnimalDetail_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_livestockActivityService_AnimalDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestockActivityService_AnimalDetail_descriptor,
        new java.lang.String[] { "AnimalID", "TypeOfAnimal", "DateOfBirth", "DateNextVaccine", });
    internal_static_livestockActivityService_SetAnimalDetailsReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_livestockActivityService_SetAnimalDetailsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestockActivityService_SetAnimalDetailsReply_descriptor,
        new java.lang.String[] { "SetAnimalDetailsReply", });
    internal_static_livestockActivityService_AnimalTimeSpan_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_livestockActivityService_AnimalTimeSpan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestockActivityService_AnimalTimeSpan_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", "AnimalID", });
    internal_static_livestockActivityService_LiveHeartRate_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_livestockActivityService_LiveHeartRate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestockActivityService_LiveHeartRate_descriptor,
        new java.lang.String[] { "Bpm", "Animal", });
    internal_static_livestockActivityService_HeartRateHistory_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_livestockActivityService_HeartRateHistory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestockActivityService_HeartRateHistory_descriptor,
        new java.lang.String[] { "Bpm", "TimeStamp", "Animal", });
    internal_static_livestockActivityService_CurrentActivity_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_livestockActivityService_CurrentActivity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestockActivityService_CurrentActivity_descriptor,
        new java.lang.String[] { "Animal", "Activity", });
    internal_static_livestockActivityService_AnimalHealthInfo_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_livestockActivityService_AnimalHealthInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestockActivityService_AnimalHealthInfo_descriptor,
        new java.lang.String[] { "ReportDate", "MinBPM", "MaxBPM", "AvgBPM", "HealthIndicator", "Animal", });
    internal_static_livestockActivityService_Empty_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_livestockActivityService_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_livestockActivityService_Empty_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
