// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

public interface LiveHeartRateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestockActivityService.LiveHeartRate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bpm = 1;</code>
   */
  int getBpm();
}
