// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: LivestockActivityService.proto

package ds.livestockActivityService;

public interface SetAnimalDetailsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:livestockActivityService.SetAnimalDetailsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string setAnimalDetailsReply = 1;</code>
   */
  java.lang.String getSetAnimalDetailsReply();
  /**
   * <code>string setAnimalDetailsReply = 1;</code>
   */
  com.google.protobuf.ByteString
      getSetAnimalDetailsReplyBytes();
}
