// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MilkingParlourService.proto

package ds.milkingParlourService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:milkingParlourService.Empty)
    com.google.protobuf.MessageOrBuilder {
}
