// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MilkingParlourService.proto

package ds.milkingParlourService;

public interface MachineReportDateOrBuilder extends
    // @@protoc_insertion_point(interface_extends:milkingParlourService.MachineReportDate)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reportDate = 1;</code>
   */
  java.lang.String getReportDate();
  /**
   * <code>string reportDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getReportDateBytes();

  /**
   * <code>.milkingParlourService.MachineId machineID = 2;</code>
   */
  boolean hasMachineID();
  /**
   * <code>.milkingParlourService.MachineId machineID = 2;</code>
   */
  ds.milkingParlourService.MachineId getMachineID();
  /**
   * <code>.milkingParlourService.MachineId machineID = 2;</code>
   */
  ds.milkingParlourService.MachineIdOrBuilder getMachineIDOrBuilder();
}
