// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MilkingParlourService.proto

package ds.milkingParlourService;

public interface MachineIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:milkingParlourService.MachineId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();
}
