// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MilkingParlourService.proto

package ds.milkingParlourService;

public interface MachineTimeSpanOrBuilder extends
    // @@protoc_insertion_point(interface_extends:milkingParlourService.MachineTimeSpan)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string startDate = 1;</code>
   */
  java.lang.String getStartDate();
  /**
   * <code>string startDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getStartDateBytes();

  /**
   * <code>string endDate = 2;</code>
   */
  java.lang.String getEndDate();
  /**
   * <code>string endDate = 2;</code>
   */
  com.google.protobuf.ByteString
      getEndDateBytes();
}
