// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MilkingParlourService.proto

package ds.milkingParlourService;

public interface MilkQuantityOrBuilder extends
    // @@protoc_insertion_point(interface_extends:milkingParlourService.MilkQuantity)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float volumeLitres = 1;</code>
   */
  float getVolumeLitres();
}
