// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MilkingParlourService.proto

package ds.milkingParlourService;

public interface MilkReportOrBuilder extends
    // @@protoc_insertion_point(interface_extends:milkingParlourService.MilkReport)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string reportDate = 1;</code>
   */
  java.lang.String getReportDate();
  /**
   * <code>string reportDate = 1;</code>
   */
  com.google.protobuf.ByteString
      getReportDateBytes();

  /**
   * <code>.milkingParlourService.MachineTimeSpan reportTimeSpan = 2;</code>
   */
  boolean hasReportTimeSpan();
  /**
   * <code>.milkingParlourService.MachineTimeSpan reportTimeSpan = 2;</code>
   */
  ds.milkingParlourService.MachineTimeSpan getReportTimeSpan();
  /**
   * <code>.milkingParlourService.MachineTimeSpan reportTimeSpan = 2;</code>
   */
  ds.milkingParlourService.MachineTimeSpanOrBuilder getReportTimeSpanOrBuilder();

  /**
   * <code>float volumeLitres = 3;</code>
   */
  float getVolumeLitres();

  /**
   * <code>float heatedTemperature = 4;</code>
   */
  float getHeatedTemperature();

  /**
   * <code>float heatedDuration = 5;</code>
   */
  float getHeatedDuration();

  /**
   * <code>float chilledTemperature = 6;</code>
   */
  float getChilledTemperature();
}
