// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MilkingParlourService.proto

package ds.milkingParlourService;

public final class MilkingParlourServiceImpl {
  private MilkingParlourServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_milkingParlourService_MachineId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_milkingParlourService_MachineId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_milkingParlourService_MachineDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_milkingParlourService_MachineDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_milkingParlourService_SetMachineDetailsReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_milkingParlourService_SetMachineDetailsReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_milkingParlourService_MachineTimeSpan_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_milkingParlourService_MachineTimeSpan_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_milkingParlourService_MilkQuantity_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_milkingParlourService_MilkQuantity_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_milkingParlourService_MilkReport_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_milkingParlourService_MilkReport_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033MilkingParlourService.proto\022\025milkingPa" +
      "rlourService\"\027\n\tMachineId\022\n\n\002id\030\001 \001(\005\"t\n" +
      "\rMachineDetail\0223\n\tmachineID\030\001 \001(\0132 .milk" +
      "ingParlourService.MachineId\022\025\n\rdateInsta" +
      "lled\030\002 \001(\t\022\027\n\017dateNextService\030\003 \001(\t\"8\n\026S" +
      "etMachineDetailsReply\022\036\n\026setMachineDetai" +
      "lsReply\030\001 \001(\t\"j\n\017MachineTimeSpan\022\021\n\tstar" +
      "tDate\030\001 \001(\t\022\017\n\007endDate\030\002 \001(\t\0223\n\tmachineI" +
      "D\030\003 \001(\0132 .milkingParlourService.MachineI" +
      "d\"$\n\014MilkQuantity\022\024\n\014volumeLitres\030\001 \001(\002\"" +
      "\336\001\n\nMilkReport\022\022\n\nreportDate\030\001 \001(\t\022>\n\016re" +
      "portTimeSpan\030\002 \001(\0132&.milkingParlourServi" +
      "ce.MachineTimeSpan\022\024\n\014volumeLitres\030\003 \001(\002" +
      "\022\031\n\021heatedTemperature\030\004 \001(\002\022\026\n\016heatedDur" +
      "ation\030\005 \001(\002\022\032\n\022chilledTemperature\030\006 \001(\002\022" +
      "\027\n\017dateNextService\030\007 \001(\t2\302\002\n\025MilkingParl" +
      "ourService\022l\n\021SetMachineDetails\022$.milkin" +
      "gParlourService.MachineDetail\032-.milkingP" +
      "arlourService.SetMachineDetailsReply\"\000(\001" +
      "\022[\n\016GetMilkReports\022 .milkingParlourServi" +
      "ce.MachineId\032!.milkingParlourService.Mil" +
      "kReport\"\000(\0010\001\022^\n\rGetMilkVolume\022&.milking" +
      "ParlourService.MachineTimeSpan\032#.milking" +
      "ParlourService.MilkQuantity\"\000B7\n\030ds.milk" +
      "ingParlourServiceB\031MilkingParlourService" +
      "ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_milkingParlourService_MachineId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_milkingParlourService_MachineId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_milkingParlourService_MachineId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_milkingParlourService_MachineDetail_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_milkingParlourService_MachineDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_milkingParlourService_MachineDetail_descriptor,
        new java.lang.String[] { "MachineID", "DateInstalled", "DateNextService", });
    internal_static_milkingParlourService_SetMachineDetailsReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_milkingParlourService_SetMachineDetailsReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_milkingParlourService_SetMachineDetailsReply_descriptor,
        new java.lang.String[] { "SetMachineDetailsReply", });
    internal_static_milkingParlourService_MachineTimeSpan_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_milkingParlourService_MachineTimeSpan_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_milkingParlourService_MachineTimeSpan_descriptor,
        new java.lang.String[] { "StartDate", "EndDate", "MachineID", });
    internal_static_milkingParlourService_MilkQuantity_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_milkingParlourService_MilkQuantity_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_milkingParlourService_MilkQuantity_descriptor,
        new java.lang.String[] { "VolumeLitres", });
    internal_static_milkingParlourService_MilkReport_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_milkingParlourService_MilkReport_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_milkingParlourService_MilkReport_descriptor,
        new java.lang.String[] { "ReportDate", "ReportTimeSpan", "VolumeLitres", "HeatedTemperature", "HeatedDuration", "ChilledTemperature", "DateNextService", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
