// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MilkingParlourService.proto

package ds.milkingParlourService;

public interface SetMachineDetailsReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:milkingParlourService.SetMachineDetailsReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string setMachineDetailsReply = 1;</code>
   */
  java.lang.String getSetMachineDetailsReply();
  /**
   * <code>string setMachineDetailsReply = 1;</code>
   */
  com.google.protobuf.ByteString
      getSetMachineDetailsReplyBytes();
}
